NetStandardApp_net461/Controllers/AuthorizationController.cs
using System;
using System.Configuration;
using System.Web.Mvc;
using System.Net.Http;
using Xero.NetStandard.OAuth2.Client;
using Xero.NetStandard.OAuth2.Config;
using Microsoft.Extensions.DependencyInjection;
using Xero.NetStandard.OAuth2.Token;
using Xero.NetStandard.OAuth2.Models;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace NetStandardApp_net461.Controllers
{
    public class AuthorizationController : Controller
    {

        // GET: /Authorization
        public ActionResult Index()
        {
            var serviceProvider = new ServiceCollection().AddHttpClient().BuildServiceProvider();
            var httpClientFactory = serviceProvider.GetService<IHttpClientFactory>();

            XeroConfiguration XeroConfig = new XeroConfiguration
            {
                ClientId = ConfigurationManager.AppSettings["XeroClientId"],
                ClientSecret = ConfigurationManager.AppSettings["XeroClientSecret"],
                CallbackUri = new Uri(ConfigurationManager.AppSettings["XeroCallbackUri"]),
                Scope = ConfigurationManager.AppSettings["XeroScope"],
                State = ConfigurationManager.AppSettings["XeroState"]
            };

            var client = new XeroClient(XeroConfig, httpClientFactory);

            return Redirect(client.BuildLoginUri());
        }

        // GET: /Authorization/Callback
        public async Task<ActionResult> Callback(string code, string state)
        {
            var serviceProvider = new ServiceCollection().AddHttpClient().BuildServiceProvider();
            var httpClientFactory = serviceProvider.GetService<IHttpClientFactory>();

            XeroConfiguration XeroConfig = new XeroConfiguration
            {
                ClientId = ConfigurationManager.AppSettings["XeroClientId"],
                ClientSecret = ConfigurationManager.AppSettings["XeroClientSecret"],
                CallbackUri = new Uri(ConfigurationManager.AppSettings["XeroCallbackUri"]),
                Scope = ConfigurationManager.AppSettings["XeroScope"],
                State = ConfigurationManager.AppSettings["XeroState"]
            };

            var client = new XeroClient(XeroConfig, httpClientFactory);

            var xeroToken = (XeroOAuth2Token)await client.RequestXeroTokenAsync(code);
            List<Tenant> tenants = await client.GetConnectionsAsync(xeroToken);

            Tenant firstTenant = tenants[0];

            TokenUtilities.StoreToken(xeroToken);

            return RedirectToAction("Index", "OrganisationInfo");
        }


    }
}

NetStandardApp_net461/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NetStandardApp_net461.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            bool firstTimeConnection = false;

            if (TokenUtilities.TokenExists())
            {
                firstTimeConnection = true;
            }

            return View(firstTimeConnection);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NetStandardApp_net461/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NetStandardApp_net461/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NetStandardApp_net461/Views/Home/Index.cshtml
@model dynamic

@{
    ViewData["Title"] = "Home Page";
}

<div>
    @if (Model == false)
    {
        <p>
            <button onclick="location.href='@Url.Action("Index", "Authorization")'">Connect to Xero</button>
        </p>
    }
    else
    {
        <p> You are connected to your Xero organisation. Try the following operations:</p>

        <p>
            <button onclick="location.href='@Url.Action("Index", "Authorization")'">Reauthorize Xero</button>
        </p>

        <p>
            <button onclick="location.href='@Url.Action("Index", "OrganisationInfo")'">Get Organisation Information</button>
        </p>

        <p>
            <button onclick="location.href='@Url.Action("Index", "ContactsInfo")'">Get Contacts</button>
        </p>

        <p>
            <button onclick="location.href='@Url.Action("Create", "ContactsInfo")'">Create A Contact</button>
        </p>
    }

</div>